/* 3D Block Rotation — Shepard & Metzler style. Two 3D polycube figures are
   shown side by side. Figure B is EITHER the same object as A (just rotated in
   space) OR its mirror image. Decide same/mirror in a 60-second run; +1 per
   correct answer, wrong answers flash red but never end the run.

   Correctness is integer-exact:
     · A shape is an array of unit-cube coords [x,y,z], a connected polycube.
     · The 24 proper rotations are generated by composing 90deg integer turns
       about X / Y / Z (rot90x/y/z below — each has determinant +1, so any
       composition is a pure rotation and can NEVER turn a shape into its
       mirror).
     · SAME  trial: B = A's shape under a DIFFERENT random rotation (det +1).
     · MIRROR trial: B = reflect(x -> -x, det -1) THEN a random rotation, so the
       net transform has determinant -1 and is provably unreachable by rotation.
     · Generation rejects ACHIRAL shapes (those whose mirror equals some rotation
       of themselves) via a rotation-set disjointness test, so a "mirror" trial
       is always genuinely distinguishable from "same". */
NERDBOX.injectStyle("rotate3d", `
  .r3d-wrap { position: relative; width: 100%; max-width: 560px; display: flex; flex-direction: column; align-items: center; gap: 1.3rem; margin: 0 auto; }
  .r3d-board { display: flex; align-items: stretch; justify-content: center; gap: 0.9rem; width: 100%; }
  .r3d-pane { flex: 1 1 0; display: flex; flex-direction: column; align-items: center; gap: 0.55rem; }
  .r3d-stage { width: 100%; aspect-ratio: 1 / 1; border-radius: 16px; background: var(--bg-alt); border: 1px solid color-mix(in srgb, var(--text) 8%, transparent); display: flex; align-items: center; justify-content: center; transition: box-shadow 0.14s, border-color 0.14s; }
  .r3d-stage canvas { width: 100%; height: 100%; display: block; }
  .r3d-label { font-family: "JetBrains Mono", monospace; font-size: 0.72rem; letter-spacing: 0.08em; text-transform: uppercase; color: var(--sub); }
  .r3d-vs { align-self: center; font-family: "JetBrains Mono", monospace; font-size: 1.2rem; color: var(--sub-alt); user-select: none; }
  .r3d-controls { display: flex; gap: 0.9rem; width: 100%; max-width: 420px; }
  .r3d-choice { flex: 1 1 0; border: 1px solid var(--sub-alt); background: transparent; color: var(--text); border-radius: 12px; padding: 0.85rem 0.6rem; font-family: "JetBrains Mono", monospace; font-size: 1.05rem; font-weight: 500; cursor: pointer; transition: color 0.14s, border-color 0.14s, background 0.14s, transform 0.08s; }
  .r3d-choice:hover { border-color: var(--accent); background: var(--bg-alt); }
  .r3d-choice:active { transform: translateY(1px); }
  .r3d-controls.r3d-locked .r3d-choice { pointer-events: none; opacity: 0.55; }
  .r3d-hint { font-family: "JetBrains Mono", monospace; font-size: 0.82rem; color: var(--sub); text-align: center; min-height: 1.2em; }
  .r3d-hint b { color: var(--accent); font-weight: 500; }
  .r3d-wrap.r3d-good .r3d-stage { border-color: var(--go); box-shadow: 0 0 0 1px var(--go), 0 0 24px -8px var(--go); }
  .r3d-wrap.r3d-bad .r3d-stage { border-color: var(--error); box-shadow: 0 0 0 1px var(--error), 0 0 24px -8px var(--error); }
`);

NERDBOX.register({
  id: "rotate3d",
  name: "3D Block Rotation",
  tagline: "same shape, or its mirror?",
  category: "perception",
  difficulty: "extreme",
  scoreMode: "max",
  formatScore: function (v) { return v + " streak"; },
  icon: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2 21 7v10l-9 5-9-5V7z"/><path d="M12 2v20"/><path d="M3 7l9 5 9-5"/></svg>',
  mount: function (root, ctx) {
    var el = ctx.util.el, rand = ctx.util.rand, shuffle = ctx.util.shuffle;

    /* ---- config ---- */
    var ROUND = 60;          // seconds per run
    var MIN_CUBES = 5, MAX_CUBES = 7;
    var U = 26;              // cube screen size in px
    var FLASH_MS = 200;

    /* ---- state ---- */
    var running = false;
    var locked = false;
    var timer = null;        // 1s countdown interval
    var flashT = null;       // answer-flash timeout
    var keyHandler = null;   // document keydown listener
    var timeLeft = ROUND;
    var score = 0;           // best streak this run
    var streak = 0;          // current consecutive-correct run
    var curMirror = false;   // truth of the trial currently shown

    /* ---- integer 90deg rotations (right-handed, all determinant +1) ---- */
    function rot90x(p) { return [p[0], -p[2], p[1]]; }
    function rot90y(p) { return [p[2], p[1], -p[0]]; }
    function rot90z(p) { return [-p[1], p[0], p[2]]; }
    function reflectX(p) { return [-p[0], p[1], p[2]]; }

    function applyAll(shape, fn) {
      var out = [], i;
      for (i = 0; i < shape.length; i++) out.push(fn(shape[i]));
      return out;
    }

    // a random proper rotation: compose a handful of axis turns (det stays +1).
    function randomRotation(shape) {
      var s = shape, n = 3 + rand(6), i; // 3..8 turns
      for (i = 0; i < n; i++) {
        var r = rand(3);
        s = applyAll(s, r === 0 ? rot90x : (r === 1 ? rot90y : rot90z));
      }
      return s;
    }

    /* ---- canonical fingerprint (shift to origin, sort coords) ---- */
    function key(shape) {
      var minX = Infinity, minY = Infinity, minZ = Infinity, i, p;
      for (i = 0; i < shape.length; i++) {
        p = shape[i];
        if (p[0] < minX) minX = p[0];
        if (p[1] < minY) minY = p[1];
        if (p[2] < minZ) minZ = p[2];
      }
      var pts = [];
      for (i = 0; i < shape.length; i++) {
        p = shape[i];
        pts.push((p[0] - minX) + "," + (p[1] - minY) + "," + (p[2] - minZ));
      }
      pts.sort();
      return pts.join(";");
    }

    // the set of fingerprints over all orientations reachable by the 24 proper
    // rotations (generated by repeatedly applying the three axis turns until the
    // closure stops growing — bounded, never more than 24 entries).
    function rotationSet(shape) {
      var seen = {}, queue = [shape], guard = 0;
      seen[key(shape)] = true;
      while (queue.length && guard++ < 200) {
        var cur = queue.shift();
        var nexts = [applyAll(cur, rot90x), applyAll(cur, rot90y), applyAll(cur, rot90z)];
        for (var j = 0; j < nexts.length; j++) {
          var k = key(nexts[j]);
          if (!seen[k]) { seen[k] = true; queue.push(nexts[j]); }
        }
      }
      return seen;
    }

    // chiral := the shape's mirror shares NO orientation with the shape itself.
    function isChiral(shape) {
      var a = rotationSet(shape);
      var b = rotationSet(applyAll(shape, reflectX));
      for (var k in b) if (a[k]) return false;
      return true;
    }

    /* ---- polycube generation (bounded random growth) ---- */
    function growPolycube() {
      var target = MIN_CUBES + rand(MAX_CUBES - MIN_CUBES + 1);
      var occ = {}, cubes = [[0, 0, 0]];
      occ["0,0,0"] = true;
      var dirs = [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1]];
      var guard = 0;
      while (cubes.length < target && guard++ < 400) {
        var from = cubes[rand(cubes.length)];
        var d = shuffle(dirs.slice());
        for (var i = 0; i < d.length; i++) {
          var nx = from[0] + d[i][0], ny = from[1] + d[i][1], nz = from[2] + d[i][2];
          var kk = nx + "," + ny + "," + nz;
          if (occ[kk]) continue;
          occ[kk] = true; cubes.push([nx, ny, nz]);
          break;
        }
      }
      return cubes;
    }

    function makeChiralShape() {
      for (var t = 0; t < 60; t++) {
        var c = growPolycube();
        if (c.length >= MIN_CUBES && isChiral(c)) return c;
      }
      // fallback: a known chiral hexacube (an L/Z 3D "tetris" screw shape)
      return [[0, 0, 0], [1, 0, 0], [2, 0, 0], [2, 1, 0], [2, 1, 1], [2, 2, 1]];
    }

    /* ---- colours derived from --accent ---- */
    function parseRGB(str) {
      str = (str || "").trim();
      var m;
      if (str.charAt(0) === "#") {
        var h = str.slice(1);
        if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
        var n = parseInt(h, 16);
        return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
      }
      m = str.match(/(\d+)[ ,]+(\d+)[ ,]+(\d+)/);
      if (m) return [+m[1], +m[2], +m[3]];
      return [226, 183, 20]; // serika accent fallback
    }
    function shade(rgb, f) {
      function c(v) { return Math.max(0, Math.min(255, Math.round(v * f))); }
      return "rgb(" + c(rgb[0]) + "," + c(rgb[1]) + "," + c(rgb[2]) + ")";
    }

    /* ---- isometric render onto a canvas ---- */
    function project(p, u) {
      return [(p[0] - p[2]) * u * 0.866, (p[0] + p[2]) * u * 0.5 - p[1] * u];
    }

    function draw(canvas, shape) {
      var dpr = window.devicePixelRatio || 1;
      var box = canvas.getBoundingClientRect();
      var w = Math.max(80, Math.round(box.width)), h = w; // square stage
      canvas.width = w * dpr; canvas.height = h * dpr;
      var g = canvas.getContext("2d");
      g.setTransform(dpr, 0, 0, dpr, 0, 0);
      g.clearRect(0, 0, w, h);

      // fit: project all cube centres, find span, pick offset to centre
      var minSx = Infinity, maxSx = -Infinity, minSy = Infinity, maxSy = -Infinity, i, s;
      for (i = 0; i < shape.length; i++) {
        s = project(shape[i], U);
        if (s[0] < minSx) minSx = s[0];
        if (s[0] > maxSx) maxSx = s[0];
        if (s[1] < minSy) minSy = s[1];
        if (s[1] > maxSy) maxSy = s[1];
      }
      // account for the cube footprint (half a cube around centres on each side)
      var pad = U * 1.0;
      var cx = w / 2 - (minSx + maxSx) / 2;
      var cy = h / 2 - (minSy + maxSy) / 2;
      // scale down if it would overflow the stage
      var spanX = (maxSx - minSx) + pad * 2, spanY = (maxSy - minSy) + pad * 2;
      var scale = Math.min(1, (w - 8) / spanX, (h - 8) / spanY);

      var accent = parseRGB(ctx.themeColor("--accent"));
      var bg = ctx.themeColor("--bg") || "#111";
      var topCol = shade(accent, 1.0);
      var leftCol = shade(accent, 0.62);
      var rightCol = shade(accent, 0.40);

      // back-to-front painter's order: smaller (x + z - y) is further away
      var order = shape.slice();
      order.sort(function (a, b) { return (a[0] + a[2] - a[1]) - (b[0] + b[2] - b[1]); });

      var ux = U * 0.866 * scale, uy = U * 0.5 * scale, uh = U * scale;

      function pt(p) {
        var sx = (p[0] - p[2]) * ux + cx;
        var sy = (p[0] + p[2]) * uy - p[1] * uh + cy;
        return [sx, sy];
      }
      function quad(pts, fill) {
        g.beginPath();
        g.moveTo(pts[0][0], pts[0][1]);
        for (var q = 1; q < pts.length; q++) g.lineTo(pts[q][0], pts[q][1]);
        g.closePath();
        g.fillStyle = fill;
        g.fill();
        g.lineWidth = 1.2;
        g.strokeStyle = bg;
        g.stroke();
      }

      for (i = 0; i < order.length; i++) {
        var p = order[i];
        // eight corners of the unit cube in projected screen space
        var c000 = pt([p[0], p[1], p[2]]);
        var c100 = pt([p[0] + 1, p[1], p[2]]);
        var c001 = pt([p[0], p[1], p[2] + 1]);
        var c101 = pt([p[0] + 1, p[1], p[2] + 1]);
        var c010 = pt([p[0], p[1] + 1, p[2]]);
        var c110 = pt([p[0] + 1, p[1] + 1, p[2]]);
        var c011 = pt([p[0], p[1] + 1, p[2] + 1]);
        var c111 = pt([p[0] + 1, p[1] + 1, p[2] + 1]);
        // TOP face (y+1 plane), LEFT face (toward -? ) and RIGHT face — only the
        // three faces visible from this fixed iso camera are drawn.
        quad([c010, c110, c111, c011], topCol);    // top
        quad([c000, c010, c011, c001], leftCol);   // left (x const)
        quad([c001, c011, c111, c101], rightCol);  // right (z+1 const)
      }
    }

    /* ---- DOM ---- */
    var status = el("div", "g-status", "");

    var canvasA = document.createElement("canvas");
    var stageA = el("div", "r3d-stage");
    stageA.appendChild(canvasA);
    var paneA = el("div", "r3d-pane");
    paneA.appendChild(stageA);
    paneA.appendChild(el("div", "r3d-label", "figure A"));

    var vs = el("div", "r3d-vs", "vs");

    var canvasB = document.createElement("canvas");
    var stageB = el("div", "r3d-stage");
    stageB.appendChild(canvasB);
    var paneB = el("div", "r3d-pane");
    paneB.appendChild(stageB);
    paneB.appendChild(el("div", "r3d-label", "figure B"));

    var board = el("div", "r3d-board");
    board.appendChild(paneA);
    board.appendChild(vs);
    board.appendChild(paneB);

    var sameBtn = el("button", "g-btn r3d-choice", "◧ Same");
    var mirrorBtn = el("button", "g-btn r3d-choice", "⇄ Mirror");
    sameBtn.type = "button";
    mirrorBtn.type = "button";
    mirrorBtn.style.background = "var(--sub)";
    var controls = el("div", "r3d-controls");
    controls.appendChild(sameBtn);
    controls.appendChild(mirrorBtn);

    var hint = el("div", "r3d-hint",
      'is figure <b>B</b> the same block rotated, or its <b>mirror</b>? (keys S / M)');

    var overlay = el("div", "g-overlay");

    var wrap = el("div", "r3d-wrap");
    wrap.appendChild(board);
    wrap.appendChild(controls);
    wrap.appendChild(hint);
    wrap.appendChild(overlay);

    root.appendChild(status);
    root.appendChild(wrap);

    /* ---- helpers ---- */
    function setStatus() {
      status.innerHTML =
        '<span class="gl-score">streak ' + streak + ' · best ' + score + '</span>' +
        '<span class="gl-time">' + timeLeft + 's</span>';
    }
    function lock(on) {
      locked = on;
      if (on) controls.classList.add("r3d-locked");
      else controls.classList.remove("r3d-locked");
    }
    function showOverlay(html) {
      overlay.innerHTML = html;
      var b = overlay.querySelector("button");
      if (b) b.addEventListener("click", start);
      overlay.classList.add("show");
    }

    /* ---- trial flow ---- */
    function nextTrial() {
      var shape = makeChiralShape();
      var figA = randomRotation(shape);
      curMirror = rand(2) === 0;

      var base = curMirror ? applyAll(shape, reflectX) : shape;
      var figB = randomRotation(base);
      // for a SAME trial, avoid an identical pose (too easy / a giveaway):
      // re-roll B's rotation a few times until its fingerprint differs from A.
      if (!curMirror) {
        var ka = key(figA), guard = 0;
        while (key(figB) === ka && guard++ < 12) figB = randomRotation(shape);
      }

      draw(canvasA, figA);
      draw(canvasB, figB);
      lock(false);
    }

    function flash(good) {
      var cls = good ? "r3d-good" : "r3d-bad";
      wrap.classList.remove("r3d-good", "r3d-bad");
      void wrap.offsetWidth; // reflow so the same class re-triggers
      wrap.classList.add(cls);
      if (flashT) clearTimeout(flashT);
      flashT = setTimeout(function () {
        flashT = null;
        wrap.classList.remove("r3d-good", "r3d-bad");
        if (running) nextTrial();
      }, FLASH_MS);
    }

    function answer(saidMirror) {
      if (!running || locked) return;
      lock(true);
      if (saidMirror === curMirror) {
        streak++;
        if (streak > score) { score = streak; ctx.submitScore(score); }
        setStatus();
        flash(true);
      } else {
        streak = 0;            // a wrong answer breaks the streak — no spam farming
        setStatus();
        flash(false);
      }
    }

    sameBtn.addEventListener("click", function () { answer(false); });
    mirrorBtn.addEventListener("click", function () { answer(true); });

    keyHandler = function (e) {
      if (!running) return;
      var k = (e.key || "").toLowerCase();
      if (k === "s") { e.preventDefault(); answer(false); }
      else if (k === "m") { e.preventDefault(); answer(true); }
    };
    document.addEventListener("keydown", keyHandler);

    /* ---- round lifecycle ---- */
    function tick() {
      timeLeft--;
      if (timeLeft <= 0) {
        timeLeft = 0;
        setStatus();
        end();
        return;
      }
      setStatus();
    }

    function start() {
      if (timer) { clearInterval(timer); timer = null; }
      if (flashT) { clearTimeout(flashT); flashT = null; }
      running = true;
      score = 0;
      streak = 0;
      timeLeft = ROUND;
      wrap.classList.remove("r3d-good", "r3d-bad");
      overlay.classList.remove("show");
      setStatus();
      nextTrial();
      timer = setInterval(tick, 1000);
    }

    function end() {
      running = false;
      lock(true);
      if (timer) { clearInterval(timer); timer = null; }
      if (flashT) { clearTimeout(flashT); flashT = null; }
      wrap.classList.remove("r3d-good", "r3d-bad");
      var best = ctx.submitScore(score);
      showOverlay(
        '<div class="g-result">' +
          '<div class="g-big">' + score + '</div>' +
          '<div class="g-sub">' + (best ? "new best! · " : "") + 'best streak</div>' +
          '<button class="g-btn">play again</button>' +
        '</div>'
      );
    }

    /* ---- initial idle screen ---- */
    status.textContent = "60 seconds · same shape, or its mirror?";
    lock(true);
    (function () {
      // calm static preview behind the overlay
      var prev = makeChiralShape();
      draw(canvasA, randomRotation(prev));
      draw(canvasB, randomRotation(prev));
    })();
    showOverlay(
      '<div class="g-result">' +
        '<div class="g-sub" style="margin-bottom:.4rem">rotated copy, or mirror image? · 60s</div>' +
        '<button class="g-btn">start</button>' +
      '</div>'
    );

    /* ---- teardown: stop the run, clear timers, drop the key listener ---- */
    return function () {
      running = false;
      locked = true;
      if (timer) { clearInterval(timer); timer = null; }
      if (flashT) { clearTimeout(flashT); flashT = null; }
      if (keyHandler) { document.removeEventListener("keydown", keyHandler); keyHandler = null; }
    };
  }
});
